### ISSUE TITLE
Error: Object has been disposed

### ISSUE THREAD

**Issue by shinyford** [luigi-rosso/flutter-inner-shadow#1]
Hi! I've been trying to use `InnerShadow`, but keep hitting the following error (usually when scrolling fast through a `ListView` containing images covered by an `InnerShadow`):

```
The following message was thrown during paint():
Object has been disposed.

The relevant error-causing widget was
    InnerShadow
When the exception was thrown, this was the stack
#0      Canvas._saveLayer  (dart:ui/painting.dart:3436:64)
#1      Canvas.saveLayer  (dart:ui/painting.dart:3425:7)
#2      RenderInnerShadow.paint
#3      RenderObject._paintWithContext
#4      PaintingContext.paintChild
...
The following RenderObject was being processed when the exception was fired: RenderInnerShadow#bfa4b
RenderObject: RenderInnerShadow#bfa4b
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=202.7, h=117.6)
    size: Size(202.7, 117.6)
    child: RenderColorFilter#6d258
        needs compositing
        parentData: <none> (can use size)
        constraints: BoxConstraints(w=202.7, h=117.6)
        size: Size(202.7, 117.6)
        child: RenderSemanticsAnnotations#013b2
            parentData: <none> (can use size)
            constraints: BoxConstraints(w=202.7, h=117.6)
            size: Size(202.7, 117.6)
            child: RenderImage#4a33e
                parentData: <none> (can use size)
                constraints: BoxConstraints(w=202.7, h=117.6)
                size: Size(202.7, 117.6)
                image: [500×281]
                fit: cover
                alignment: center
                invertColors: false
                filterQuality: low
```

The inner workings of `RenderObject`s are really not my forte, so I'm not sure where to start debugging this - and I just wondered if you'd seen that before as an issue, and could give me a pointer?

FWIW `InnerShadow` is being used inside a stateless widget,  so I can't see how `paint` could be being called at a point when the parent is disposed, or `InnerShadow` itself. (But as I say, not my forte.) 

It's the `saveLayer` on line 81 of the widget that seems to be having the issue.

Thanks in advance!

**Comment by chloe722** [comment]
I have the same issue

**Comment by bounty1342** [comment]
One easy way to reproduce is to place a TextFormField as a child.

Does any of you find a solution ?

Thanks

**Comment by jaysonss** [comment]
this issue is caused by `canvas reference has changed` , so try to replace ` canvas.save ` with `context.canvas.save`

**Comment by coredeveloper** [comment]
Solution: 
delete var canvas = context.canvas;
and replace every entry with 
context.canvas...
Hope I don't have to explain why it happening.

**Comment by jaysonss** [comment]
@all This is a long story, but I'll keep it as simple as possible.
1. TextField has `RepatintBoundary` child
2.  PaintContext `paintChild` function is:

```
void paintChild(RenderObject child, Offset offset) {
    if (child.isRepaintBoundary) {
      stopRecordingIfNeeded();
      _compositeChild(child, offset);
    } else {
      child._paintWithContext(this, offset);
    }
  }
```
3. `stopRecordingIfNeeded` function will rest `_canvas` reference to null
4. when use PaintContext again, it will call `_startRecording` function to make new `_canvas`
5. If you keep `canvas` reference, oooops~

ps: If you look at PaintContext source code , you'll find this
```
  /// The canvas on which to paint.
  ///
  /// The current canvas can change whenever you paint a child using this
  /// context, which means it's fragile to hold a reference to the canvas
  /// returned by this getter.
  @override
  Canvas get canvas {
    if (_canvas == null)
      _startRecording();
    return _canvas;
  }
```
So it is not a good habit to keep `canvas` reference.


Paste other version I found on stackoverflow: https://gist.github.com/Jaysonss/cf4a9760c2cb484d2a1badbe8aed34f9

**Comment by luigi-rosso** [comment]
Thanks for reporting and investigating! Should be fixed now, feel free to re-open if still run into problems with this. Btw, this repo was mostly just an exploration, not meant to be a package, but feel free to make one if you find it valuable.
